defaults: &defaults
  # IBM Mode (test/production)
  # Used in three places: q/paypal_notify, order.paypal_url, order.to_fax
  ibm_mode:               test
#  ibm_domain:             localhost

  # Dropbox Information
#  app_key:                <%=ENV['app_key']%>
#  app_secret:             <%=ENV['app_secret']%>
#  access_token:           <%=ENV['access_token']%>
#  access_token_secret:    <%=ENV['access_token_secret']%>
#  user_id:                <%=ENV['user_id']%>

  # Interfax Information
  interfax_url:           https://ws.interfax.net/dfs.asmx?WSDL
  interfax_usr:           <%=ENV['interfax_usr']%>
  interfax_pwd:           <%=ENV['interfax_pwd']%>

  # Google Information
  google_usr:             <%=ENV['google_usr']%>
  google_pwd:             <%=ENV['google_pwd']%>

  # Paypal Information
  paypal_email:            wanfenghuaian@hotmail.com
  paypal_secret:           production_secret
  paypal_cert_id:          production_cert_id
  paypal_base_url:         https://www.paypal.com/cgi-bin/webscr
  paypal_sandbox_base_url: https://www.sandbox.paypal.com/cgi-bin/webscr

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults