defaults: &defaults
  # IBM Mode (test/production)
  # Used in three places: q/paypal_notify, order.paypal_url, order.to_fax
  ibm_mode:                test
  ibm_domain:              localhost

#  # Dropbox Information
#  app_key:                 ZZZZZZZZZZZZZZZZZZZ
#  app_secret:              ZZZZZZZZZZZZZZZZZZZ
#  access_token:            ZZZZZZZZZZZZZZZZZZZ
#  access_token_secret:     ZZZZZZZZZZZZZZZZZZZ
#  user_id:                 ZZZZZZZZZZZZZZZZZZZ

  # Interfax Information
  interfax_url:          https://ws.interfax.net/dfs.asmx?WSDL
  interfax_usr:            ZZZZZZZZZZZZZZZZZZZ
  interfax_pwd:            ZZZZZZZZZZZZZZZZZZZ

  # Google Information
  google_usr:              ZZZZZZZZZZZZZZZZZZZ
  google_pwd:              ZZZZZZZZZZZZZZZZZZZ

  # Paypal Information
  paypal_email:            production@example.com
  paypal_secret:           production_secret
  paypal_cert_id:          production_cert_id
  paypal_base_url:         https://www.paypal.com/cgi-bin/webscr
  paypal_sandbox_base_url: https://www.sandbox.paypal.com/cgi-bin/webscr

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
