defaults: &defaults
  # Dropbox Information
  app_key:               ZZZZZZZZZZZZZZZZZZZ
  app_secret:            ZZZZZZZZZZZZZZZZZZZ
  access_token:          ZZZZZZZZZZZZZZZZZZZ
  access_token_secret:   ZZZZZZZZZZZZZZZZZZZ
  user_id:               ZZZZZZZZZZZZZZZZZZZ

  # Interfax Information
  interfax_url:    https://ws.interfax.net/dfs.asmx?WSDL
  interfax_usr:    ZZZZZZZZZZZZZZZZZZZ
  interfax_pwd:    ZZZZZZZZZZZZZZZZZZZ



  # IBM Mode (test/production)
  ibm_mode:        test

production:
  <<: *defaults

  domain: localhost
  paypal_base_url: https://www.paypal.com/cgi-bin/webscr

development:
  <<: *defaults

  domain: localhost

  paypal_base_url: https://www.sandbox.paypal.com/cgi-bin/webscr

test:
  <<: *defaults

  domain: localhost

  paypal_email:    test@example.com