defaults: &defaults
  # Dropbox Information
  app_key:               <%=ENV['app_key']%>
  app_secret:            <%=ENV['app_secret']%>
  access_token:          <%=ENV['access_token']%>
  access_token_secret:   <%=ENV['access_token_secret']%>
  user_id:               <%=ENV['user_id']%>

  # Interfax Information
  interfax_url:    https://ws.interfax.net/dfs.asmx?WSDL
  interfax_usr:    <%=ENV['interfax_usr']%>
  interfax_pwd:    <%=ENV['interfax_pwd']%>

  # Google Information
  google_usr:            <%=ENV['google_usr']%>
  google_pwd:            <%=ENV['google_pwd']%>


  # IBM Mode (test/production)
  ibm_mode:        test

production:
  <<: *defaults

  domain: localhost
  paypal_base_url: https://www.paypal.com/cgi-bin/webscr

development:
  <<: *defaults

  domain: localhost

  paypal_base_url: https://www.sandbox.paypal.com/cgi-bin/webscr

test:
  <<: *defaults

  domain: localhost

  paypal_email:    test@example.com